"""MediaPipe hand landmark indices (21 landmarks per hand)."""

WRIST = 0
THUMB_CMC = 1
THUMB_TIP = 4
INDEX_FINGER_MCP = 5
INDEX_FINGER_TIP = 8
MIDDLE_FINGER_MCP = 9
MIDDLE_FINGER_TIP = 12
RING_FINGER_MCP = 13
RING_FINGER_TIP = 16
PINKY_MCP = 17
PINKY_TIP = 20

# Fingertips and base joints used for hand open/close kinematics.
FINGER_TIPS = (THUMB_TIP, INDEX_FINGER_TIP, MIDDLE_FINGER_TIP, RING_FINGER_TIP, PINKY_TIP)
FINGER_MCPS = (THUMB_CMC, INDEX_FINGER_MCP, MIDDLE_FINGER_MCP, RING_FINGER_MCP, PINKY_MCP)
